// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOy0g36lHJI3LPOTGr8xYsHSszhIXLzBw',
    appId: '1:572517246464:web:3c0820f92b1c387aba9ae5',
    messagingSenderId: '572517246464',
    projectId: 'journalingapp-d6445',
    authDomain: 'journalingapp-d6445.firebaseapp.com',
    storageBucket: 'journalingapp-d6445.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkh-Ui7Ou4ihtDHHXNmre0n0Rmt_suxiM',
    appId: '1:572517246464:android:be963d3b97bd32c7ba9ae5',
    messagingSenderId: '572517246464',
    projectId: 'journalingapp-d6445',
    storageBucket: 'journalingapp-d6445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfP0sRDHj5AtSCRMawg5SBRU045Yw4Mz0',
    appId: '1:572517246464:ios:a8ad80d1a4919c98ba9ae5',
    messagingSenderId: '572517246464',
    projectId: 'journalingapp-d6445',
    storageBucket: 'journalingapp-d6445.firebasestorage.app',
    iosBundleId: 'com.example.journalingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfP0sRDHj5AtSCRMawg5SBRU045Yw4Mz0',
    appId: '1:572517246464:ios:a8ad80d1a4919c98ba9ae5',
    messagingSenderId: '572517246464',
    projectId: 'journalingapp-d6445',
    storageBucket: 'journalingapp-d6445.firebasestorage.app',
    iosBundleId: 'com.example.journalingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOy0g36lHJI3LPOTGr8xYsHSszhIXLzBw',
    appId: '1:572517246464:web:c92c0cb1da32029bba9ae5',
    messagingSenderId: '572517246464',
    projectId: 'journalingapp-d6445',
    authDomain: 'journalingapp-d6445.firebaseapp.com',
    storageBucket: 'journalingapp-d6445.firebasestorage.app',
  );

}